version: '3'
services:

  web:
    container_name: web
    image: pswlove38/github-actions-demo
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: pswlove38/change-nginx
    ports:
      - 80:80
    depends_on:
      - web