name: Java CI with Gradle

# 동작 조건 설정 : main 브랜치에 push 혹은 pull request가 발생할 경우 동작한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SSH_KEY: |
    -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA1Rv7k+tYloQW8lyauCPAI6ea+LLn4mhL19v539Kv3CVJbjZRqadK
wpEeXkkSMo2NFkDxXzy2wo0TRlQVk7nlSAJSEdswDUU3+YICATLecgFekyq0hx0E5TBT01
NGWZiAX/beroybDAbFAFAh0MdsLzurf65DsNCiHAi12w5ccn1E4IvumUKOjrRQkE2Lwc3Z
zbXYt/+8yi76Crmp/vcK2embf5JIzso/DBLNfrh7U7Ct2Rbj9fLIlgJhcX8gI4Xixn4n/V
vF5bCImUFxHqu1SwJQQz910x9i7L82HU95K/6kINhwISnky3CNNNRMoutdo6jA7Jb+JXuT
PbzgptJYD+NrY4K341N6yPNdIJW4oZusRlozeBemic1iob6/Ozc3cMNZ13UAEOcdYm18k7
q4PXl619+yvxadgAXxbwOx1wbva1NOaeF1KEklSOB1PNNtoOtvMUnFCgSWQcLU0dGbUmOB
vH6JfjGRATKiVUN8L4PdXitcRPddMdriFtsF50NLAAAFkNbud13W7nddAAAAB3NzaC1yc2
EAAAGBANUb+5PrWJaEFvJcmrgjwCOnmviy5+JoS9fb+d/Sr9wlSW42UamnSsKRHl5JEjKN
jRZA8V88tsKNE0ZUFZO55UgCUhHbMA1FN/mCAgEy3nIBXpMqtIcdBOUwU9NTRlmYgF/23q
6MmwwGxQBQIdDHbC87q3+uQ7DQohwItdsOXHJ9ROCL7plCjo60UJBNi8HN2c212Lf/vMou
+gq5qf73Ctnpm3+SSM7KPwwSzX64e1OwrdkW4/XyyJYCYXF/ICOF4sZ+J/1bxeWwiJlBcR
6rtUsCUEM/ddMfYuy/Nh1PeSv+pCDYcCEp5MtwjTTUTKLrXaOowOyW/iV7kz284KbSWA/j
a2OCt+NTesjzXSCVuKGbrEZaM3gXponNYqG+vzs3N3DDWdd1ABDnHWJtfJO6uD15etffsr
8WnYAF8W8DsdcG72tTTmnhdShJJUjgdTzTbaDrbzFJxQoElkHC1NHRm1Jjgbx+iX4xkQEy
olVDfC+D3V4rXET3XTHa4hbbBedDSwAAAAMBAAEAAAGAGXkZzj7lvOrBuhXwTIMWzBbprZ
aSTybRAgFXpzW43aNQrq2Bf2Txc7utme7kD5+J4MIXLUoa57sTNbyGmRIxt4oczeju9SHJ
T2Kx41DK9Bej0ArdFKrBqLTpICvRDz6XrGDcPJhZTsu0WpWOz9+L1+2AUhJozEbJSc6PZk
Vw2XfjIXAN2iCcMlntU1e26o3fiKOW6borkoNLp2KKpmEDLrRUvkqkYfYc09BKOJPL8gn+
uHdFp7gYhTh4S1JlwLlCVUcg9Pvry4esvNIeJqtygQ1hUkZS528ybQPNxnWZl5Si6FhLgA
5qxWrigENzQDdB2+mYSaP/R1fJeV4sPUqL1aJ1IyqbKh6+Ih8KRg6Hfbmr6LcdMYqGVYuc
CCIf0pHROxCG8tIxrgfL2mQ3uSJV3EajN1ydyD79M7aHk+HVegGNKxIOa0U6/MeWVX1RJW
ifTfClGDkFucZDVOmNo/oqBeHZDbDXQscAoQ76e/0CT5TYHKh9fLEa/Rlgei9NA8VhAAAA
wQDP8Ll6w4N1bPKx7mSKge/2ukVge7TzLr24DLT2uG6XC+HqGScU1+SNdruvqNpMD6tWa3
yxf3XicjYBB2Vd6ybVV0a6X3jRYJ+wqncwKb3UYhwPj/iIEYOuPNlSsLDkJ6nzbPilJiUF
UqiyvYX4F58OBw82gytxNDK/CHMTzJqsXoeKMipmxx+6aG9tkAtXR/lFVD47yczjBrn0j4
7rmgbTU5+MnVF7PULdFVCtu62jqn3uJcMcivBX0d8yr5El1pIAAADBAO3i/4+dQJ/OdiYm
fWQqoUXC4Zqu+FJFbh2BsSnwQtoQBS7uEkpNNK6uVK+Kpb70yK1Be4A9Yvs712oRl3OBmM
BLFnTzFo7uk0CijYizdBJ+TuC0rT1wXnvoGTgTxky5ax5gUlYmqPiBL1YFpib6ZXXSGdiE
mSiy/nmprCeoA4QGwgB4a0AAReHAfT4KaQL+RfEtOmmaU9KeV3SCQQLuj3ypqCCP3vPt/1
OzQK8NL0m/p+wc/A5TUUWTpXn2pYPFGwAAAMEA5VYC63zlhWK+gG6tgd94+9Q4dFqu4QYU
ACdpwLTdBeEpq37bL604oXhmihUQk2yme+q2WxM3mfTDGTCZKa6WdKenrXub0Ncv5nAPtQ
0gF2H7W1+jB+7odCQAZ4RNmms+Iyl6+NfDRJN9JUtN/5QCm6w7Z71RnY2tCEO9mhmXY3LM
5QZ6Bek3I9pfhis+fvJFWhpI7QBegjP7GFevezC243dqL+4cuUUq/zK6+WXcatUG5MCVRJ
6AYsipSVDxKs2RAAAAE3Bzd2xvdmUzOEBnbWFpbC5jb20BAgMEBQYH
-----END OPENSSH PRIVATE KEY-----

permissions:
  contents: read

jobs:
# Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    # 기본적인 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
      
    # 자바 버전 설정
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # gradlew에 실행 권한 부여
    - name: Executable to /gradlew
      run: chmod +x ./gradlew

    # 프로젝트 빌드
    - name: Project Build
      run: ./gradlew clean bootwar
        
    # 자바 Spring Boot 빌드
    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #   with:
    #     arguments: clean build

   # 3. Docker 이미지 빌드
    - name: docker image build
      run: docker build -t pswlove38/github-actions-demo .

    # 4. DockerHub 로그인
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: pswlove38
        password: a77981010!

    # 5. Docker Hub 이미지 푸시
    - name: docker Hub push
      run: docker push pswlove38/github-actions-demo

    # 6. GCP에 SSH로 접속
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 35.212.196.164
        username: pswlove38
        key: ${{ env.SSH_KEY }}
        port: 22
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull pswlove38/github-actions-demo
          sudo docker pull pswlove38/change-nginx
          docker-compose up -d
          docker image prune -f
